First commit test for 'first-commits' branch.
cisagov/pe-reports pull request #1
Opened 2021-04-29 17:49 UTC by schmelz-ctr

# First Commit Test#

## Commit/PR test by pushing minor update to requirments.txt 
- Next Steps include a full code push of version 0.0.1 ##

## ✅ Checklist ##

* [ ] This PR has an informative and human-readable title.
* [ ] Changes are limited to a single goal - _eschew scope creep!_
* [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
* [ ] All relevant type-of-change labels have been added.
* [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [ ] Tests have been added and/or modified to cover the changes in this PR.
* [ ] All new and existing tests pass.

2021-04-30 16:21 UTC, schmelz-ctr reviewed
This merge is to initialize repo and update the python-skeleton's content.

2021-04-30 18:32 UTC, jsf9k commented on requirements.txt
> +python-pptx==0.6.18
Please read the comment at the top of this file.

2021-04-30 18:40 UTC, jsf9k commented on requirements.txt
> +python-pptx==0.6.18
Also, why did you move all the source out of `src` into `cyhy/pe-reports`?  That is how it is done in [cisagov/cyhy-mailer](https://github.com/cisagov/cyhy-mailer), but that code pre-dates the skeletons and has not yet been brought into the light.

2021-04-30 19:19 UTC, jsf9k requested changes
I'm not sure if this PR is intended to ever be merged, but I have concerns since you are making an immediate turn off the skeleton highway and into the desert :smile:

2021-04-30 20:08 UTC, schmelz-ctr commented on requirements.txt
> +python-pptx==0.6.18
Your guess is correct, it is exactly why I changed src. Due to other cyhy repos. 
I was unaware the cyhy repos are older and not necessarily taken form "skeletons". We want to stay compliant so I will change to src/pe-reports. Also to give scope, we are working through some processes, a couple of steps beyond POC and coordinating some source control. It'll be a little rough in the interim, but plan to keep up with standards as we go.

2021-05-03 16:33 UTC, schmelz-ctr reviewed
Addressing the Change Request. Added back original python-skeleton directory 'src' and appended the project directory 'pe-reports' and supporting files. The 'src' directory should replace the bad directory 'cyhy' from last commit.

2021-05-04 15:34 UTC, schmelz-ctr commented
Closing Pull Request - Due to mis-configuration issues to original python-skeleton

2021-05-04 15:35 UTC, closed without merging