Add Trending to report
cisagov/pe-reports pull request #192
Opened 2022-04-29 16:00 UTC by DJensen94

Add Trending to the credentials and dark web pages of the report
## 🗣 Description ##
This PR adds Trending to two pages in the report to show how many cred breaches/mentions occured compared to the previous weeks
## 💭 Motivation and context ##
We want to give our stakeholders context for the current weeks numbers, seeing how these results compare to past weeks can help them see fluctuations more easily

## ✅ Pre-approval checklist ##

- [ X] This PR has an informative and human-readable title.
- [X ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] All new and existing tests pass.

2022-05-03 13:43 UTC, aloftus23 approved these changes
Looks good to me.

2022-05-03 13:45 UTC, aloftus23 commented
@dav3r The PRs are starting to stack up so we are numbering them by priority in the title. This is number 1 when you get the chance to review.

2022-05-06 19:06 UTC, cduhn17 approved these changes
Looks good.

2022-05-06 19:09 UTC, cduhn17 commented
@dav3r, 
Do you have a time frame of when you might get a chance to take a look at this PR? Thanks.

2022-05-06 19:14 UTC, dav3r commented
> @dav3r, Do you have a time frame of when you might get a chance to take a look at this PR? Thanks.

I'm going to take a look at it now.

2022-05-06 20:11 UTC, dav3r requested changes
Take a look at my feedback and please let me know if you have any questions.

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/charts.py
> +        plt.xticks(rotation=0)
In general, it would be nicer to see smaller, more targeted commits.  That way changes, like all of those to `charts.py` can be documented in the commit log, rather than being hidden amongst a larger commit like https://github.com/cisagov/pe-reports/pull/192/commits/311223a8034efe87cca37fe8e8183daa522b0918.

Some more comments sprinkled in with the code would also greatly improve its readability.

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/charts.py
> +        # plt.legend(loc=9, ncol=2, framealpha=0, fontsize=8, bbox_to_anchor=(0.5, -0.5))
Generally, we recommend removing commented-out/unused code.  If there is a valid reason to keep it around, please add a comment explaining why.

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/charts.py
> +        #     ax.text(totals.index[i], total + 0, round(total), ha="center")
See comment above about removing unused code.

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/charts.py
> +                    )
There is a bunch of duplicated code here.  Are the only values for `len(df.columns)` 1 or 2?  If so, you could add another outer loop like this:
```suggestion
        for col in range(len(df.columns)):
            for i, j in df[df.columns[col]].items():
                if int(j):
                    plt.annotate(
                        str(int(j)),
                        xy=(i, j),
                        textcoords="offset points",  # how to position the text
                        xytext=(
                            0,
                            5,
                        ),  # distance from text to points (x,y)
                        ha="center",  # horizontal alignment can be left, right or center
                    )
```

Note that I removed the commented-out `fontsize=2` line above.

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/data/db_query.py
> +    """Query credentials view ."""
Remove errant extra space:
```suggestion
    """Query credentials view."""
```

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/metrics.py
> +        return pw_creds
Might as well just consolidate these lines:
```suggestion
        return len(self.creds_view[self.creds_view["password_included"]])
```

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/metrics.py
> +        return df_cred
Same here:
```suggestion
        return self.creds_view.shape[0]
```

2022-05-06 20:11 UTC, dav3r commented on src/pe_reports/pages.py
> +    days = datetime.timedelta(27)
You should add a comment explaining why you are using this 27 day magic number.

2022-05-06 20:11 UTC, dav3r commented on tests/test_pe_reports.py
> +    assert result == [("12345", "Test Org 1", "TO_ID_1")]
First of all, I applaud you for adding a new test here! 👍   However, I'm not so sure that you are really testing your `get_orgs` query.  If I'm understanding this correctly (which I may not be), you are mocking up the DB connection and telling it what you want the results to be (`query_result`), then you are validating that the query results are the same as what you said you wanted the results to be- which they always should be.  Am I missing something or is the `get_orgs` query not really being tested here?

2022-05-09 15:49 UTC, DJensen94 commented on src/pe_reports/charts.py
> +        plt.xticks(rotation=0)
@dav3r  resolved in commit [453382d](https://github.com/cisagov/pe-reports/pull/192/commits/453382d3e42200b666790f6dd07cf010b8a58c27)

2022-05-09 15:49 UTC, DJensen94 commented on src/pe_reports/charts.py
> +        # plt.legend(loc=9, ncol=2, framealpha=0, fontsize=8, bbox_to_anchor=(0.5, -0.5))
@dav3r issue resolved in commit [453382d](https://github.com/cisagov/pe-reports/pull/192/commits/453382d3e42200b666790f6dd07cf010b8a58c27)

2022-05-09 15:50 UTC, DJensen94 commented on src/pe_reports/charts.py
> +        #     ax.text(totals.index[i], total + 0, round(total), ha="center")
@dav3r issue was resolved in [453382d](https://github.com/cisagov/pe-reports/pull/192/commits/453382d3e42200b666790f6dd07cf010b8a58c27)

2022-05-09 17:05 UTC, DJensen94 commented on src/pe_reports/pages.py
> +    days = datetime.timedelta(27)
@dav3r resolved in commit [e0a3626](https://github.com/cisagov/pe-reports/pull/192/commits/e0a3626a892cd8b547b59f9ae0aef5a13e503765)

2022-05-09 17:32 UTC, DJensen94 commented on tests/test_pe_reports.py
> +    assert result == [("12345", "Test Org 1", "TO_ID_1")]
@dav3r removed this test in commit [b6288ae](https://github.com/cisagov/pe-reports/pull/192/commits/b6288aeebe7dcb344bb564973970e586e1988fa3)

2022-05-09 17:38 UTC, aloftus23 commented on tests/test_pe_reports.py
> +    assert result == [("12345", "Test Org 1", "TO_ID_1")]
Decided to create a new issue to write more useful tests: #198

2022-05-09 20:11 UTC, dav3r commented on tests/test_pe_reports.py
> +    assert result == [("12345", "Test Org 1", "TO_ID_1")]
Thanks @DJensen94 and @aloftus23 👍

2022-05-09 20:14 UTC, dav3r commented on src/pe_reports/charts.py
> +        # Specify axis atributes
Typo:
```suggestion
        # Specify axis attributes
```

2022-05-10 13:18 UTC, dav3r approved these changes
Once the typo mentioned [here](https://github.com/cisagov/pe-reports/pull/192#discussion_r868409603) is corrected, this one looks good to me. 👍

2022-05-10 14:01 UTC, jsf9k requested changes
I'd like to see [the two warnings from LGTM](https://github.com/cisagov/pe-reports/pull/192#issuecomment-1121421689) resolved before merging.

2022-05-10 14:25 UTC, DJensen94 commented
> I'd like to see [the two warnings from LGTM](https://github.com/cisagov/pe-reports/pull/192#issuecomment-1121421689) resolved before merging.

@dav3r , @jsf9k We are pretty positive that the warnings are unfounded, they claim that origin is not a parameter for 
grouper, but it is a new parameter:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/79864006/167652108-e356ddb9-978f-4513-b898-851240b2f08e.png">
So LGTM is out of date

2022-05-10 14:28 UTC, jsf9k commented
> > I'd like to see [the two warnings from LGTM](https://github.com/cisagov/pe-reports/pull/192#issuecomment-1121421689) resolved before merging.
> 
> @dav3r , @jsf9k We are pretty positive that the warnings are unfounded, they claim that origin is not a parameter for grouper, but it is a new parameter: <img alt="image" width="662" src="https://user-images.githubusercontent.com/79864006/167652108-e356ddb9-978f-4513-b898-851240b2f08e.png"> So LGTM is out of date

Then you should add [a suppression comment](https://lgtm.com/help/lgtm/alert-suppression#python) for those two warnings.

2022-05-10 15:25 UTC, DJensen94 commented
> > > I'd like to see [the two warnings from LGTM](https://github.com/cisagov/pe-reports/pull/192#issuecomment-1121421689) resolved before merging.
> > 
> > 
> > @dav3r , @jsf9k We are pretty positive that the warnings are unfounded, they claim that origin is not a parameter for grouper, but it is a new parameter: <img alt="image" width="662" src="https://user-images.githubusercontent.com/79864006/167652108-e356ddb9-978f-4513-b898-851240b2f08e.png"> So LGTM is out of date
> 
> Then you should add [a suppression comment](https://lgtm.com/help/lgtm/alert-suppression#python) for those two warnings.

@jsf9k we have added the suppression comment. LGTM says the warning won't be removed till after the merge occurs.

2022-05-10 16:22 UTC, jsf9k approved these changes
I can't get the LGTM thing to go away either, so I'll have to let it pass for now.

2022-05-10 16:50 UTC, merged