Add database connection config
cisagov/pe-reports pull request #91
Opened 2021-10-28 16:51 UTC by cduhn17

#  #

## 🗣 Description ##
Create a method to securely make a connection to pe-reports postgres database to use in downstream functions/classes. Resolves #76 

## 💭 Motivation and context ##
This script sets up the foundation in making a centralized single point for connections to the pe-reports database . This configuration also makes a reference to the raw credentials in place of having the raw credentials in the script.

## 🧪 Testing ##
This current PR needs to pass current `pytest /tests`

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

2021-10-28 18:08 UTC, schmelz21 reviewed
@cduhn17, Made some suggestions to the docstring definitions. Other than that looking good.

2021-10-28 18:08 UTC, schmelz21 commented on src/pe_reports/data/config.py
> +"""The file contains the postgresql dbconfig.config parsing code."""
```suggestion
"""Configuration to connect to a PostgreSQL database."""
```

2021-10-28 18:08 UTC, schmelz21 commented on src/pe_reports/data/config.py
> +    """Configure connection to creds file and returns creds."""
```suggestion
    """Pass credentials to access database."""
```

2021-10-29 16:43 UTC, dav3r requested changes
Please take a look at my suggested changes and let me know what you think.

2021-10-29 16:43 UTC, dav3r commented on src/pe_reports/data/config.py
> +    db = {}
We typically prefer this syntax for code readability, but you can take it or leave it.
```suggestion
    db = dict()
```

2021-10-29 16:43 UTC, dav3r commented on src/pe_reports/data/config.py
> +import pkg_resources
This should be switched to use the standard [`importlib.resources` module](https://docs.python.org/3/library/importlib.html#module-importlib.resources) instead of `pkg_resources`.

2021-10-29 16:43 UTC, dav3r commented on src/pe_reports/data/config.py
> +            db[param[0]] = param[1]
How about this simpler way of populating the `db` dictionary?
```suggestion
        for key, value in parser.items(section):
            db[key] = value
```

2021-11-01 21:22 UTC, cduhn17 commented
@schmelz21 
Could you review again since Ive made some changes after others have reviewed?

2021-11-01 22:40 UTC, schmelz21 commented on src/pe_reports/data/config.py
> +import pkg_resources
looks resolved here - 7b7f906 with small lint update here - 44585f4.

2021-11-01 22:41 UTC, schmelz21 approved these changes
Looks good!

2021-11-02 12:24 UTC, cduhn17 commented on src/pe_reports/data/config.py
> +import pkg_resources
@dav3r , 

I have made the change to importlib.resources per commit [7b7f906](https://github.com/cisagov/pe-reports/pull/91/commits/7b7f9069186cc360b9cb0574141d5e20513b4066). Please review this change when you have a moment. All of your other suggestions made sense and have been committed per the suggestion.

2021-11-02 13:20 UTC, dav3r commented on src/pe_reports/data/config.py
> +import pkg_resources
Looks good now, thanks!

2021-11-02 13:30 UTC, dav3r commented on src/pe_reports/data/config.py
> +    """Configure connection to creds file and returns creds."""
Why was this conversation resolved with no changes and no commentary?
Personally, I would go with something like:
```
"""Parse Postgres configuration details from database configuration file."""
```

2021-11-02 13:32 UTC, dav3r commented
@cduhn17 - Just about good to go here; I will re-review after you respond to https://github.com/cisagov/pe-reports/pull/91#discussion_r741056443.

2021-11-02 14:44 UTC, cduhn17 commented on src/pe_reports/data/config.py
> +    """Configure connection to creds file and returns creds."""
@dav3r 
I may have hit the resolve button without accepting the suggestion. I have accepted the suggestion to change the doc string  and additionally updated the doc string per your comment here per commit [699ac5e](https://github.com/cisagov/pe-reports/pull/91/commits/699ac5e01c02ae1cd420a7b527b905725835371e)

2021-11-02 14:54 UTC, dav3r commented on src/pe_reports/data/config.py
> +    """Configure connection to creds file and returns creds."""
Thanks for the clarification and the updated docstring. 👍

2021-11-02 14:56 UTC, dav3r approved these changes
Good stuff! 🎉

2021-11-02 15:01 UTC, merged